name: autopep8
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: autopep8
        uses: peter-evans/autopep8@v1.2.1
        with:
          args: --recursive --in-place --aggressive --aggressive .

