name: MATLAB Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0

      - name: Run all tests
        uses: matlab-actions/run-tests@v0
