name: autopep8
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: autopep8
        run: find src
        uses: peter-evans/autopep8@v1.2.1
        with:
          args: --recursive --in-place --aggressive --aggressive ./app.py
        
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1
